== Task 1

Создать класс `ArtistDto` с полями:

- `name` имя исполнителя
- `russian` является ли исполнителем музыки на русском языке

== Task 2

Создать jsp-страницу `create-artist.jsp`, содержащую форму для ввода имени артиста.

* форма отправляет данные в *HTTP Request* c *method POST* сервлету, который проводит *data validation*.
** если имя артиста не указано, тогда servlet должен снова перенаправить на страницу ввода данных
** если указаны верно, тогда servlet должен перенаправить на jsp-страницу `create-artist-success.jsp`, на которой нужно отобразить текст: `Artist saved.`

== Task 3

Вывести данные об исполнителе с помощью jsp-старицы `read-artist.jsp` в следующем виде:

[source,web]
----
Id: ${id}
Имя исполнителя: ${name}
Русская музыка: ${russian}
----

== Task 4

Вывести список всех исполнителей с помощью jsp-старицы `read-artists.jsp` в виде таблицы:

[source,web]
|===
|Id|Имя исполнителя
|${id}|${name}
|===

где `id` является ссылкой, которая при нажатии перенаправит на страницу данного исполнителя.



