= EL

NOTE: Если в задании не описано как хранить данные, то способ хранения выбирается самостоятельно. Это может быть: как база данных, так и файл, так и некая структура данных.

== Task 1

Создать model `Artist` с полями:

* `id` идентификатор
* `name` имя исполнителя
* `language` на каком языке чаще всего исполняется музыка

== Task 2

Создать страницу `artists-create.jsp` имеющую форму, которая отправляет данные в *HTTP Request* c *method POST* на servlet c *URL* `/artists`.

* Servlet проводит *data validation* (*валидацию данных*):
** Если имя исполнителя или его основной язык исполнения не указано, тогда servlet должен снова перенаправить на страницу ввода данных и отобразить ошибку именно у того элемента страницы, которое было незаполненно.
** Если данные указаны верно, тогда servlet должен перенаправить на jsp-страницу `artists-create-success.jsp`, на которой нужно отобразить текст: `Artist saved.`

== Task 3

Реализовать у servlet который обрабатывает *HTTP Request* `POST /artists` развилку:

* Если *HTTP header* `Content-Type` текущего запроса не имеет значения `application/x-www-form-urlencoded`, тогда servlet перенаправляет его на jsp-страницу `create-artist.jsp`, содержащую форму для ввода данных об исполнителе.
* Если *HTTP header* `Content-Type` текущего запроса не имеет значения `application/x-www-form-urlencoded`, тогда servlet работает так же, как было описано в задании выше.

== Task 4

Отправить *HTTP Request* c *method GET* на servlet c *URL* `/artists/${id}`, который перенаправит его на jsp-страницу `artists-read-by-id.jsp`. Страница выводит данные об исполнителе в следующем виде:

----
Id: `${id}`
Имя исполнителя: `${name}`
Язык исполнения: `${language}`
----

== Task 5

Отправить *HTTP Request* c *method GET* на servlet c *URL* `/artists`, который перенаправит его на jsp-страницу `artists-read-all.jsp`. Страница выводит список всех исполнителей в виде таблицы:

|===
|Id|Имя исполнителя|Язык исполнения
|`${id}`|`${name}`|`${language}`
|===

где `${id}` является и уникальным идентификатором и ссылкой, которая при нажатии перенаправит на страницу данного исполнителя.
