= EL

== Task 1

Создать класс `ArtistDto` с полями:

- `id` идентификатор
- `name` имя исполнителя
- `language` на каком языке чаще всего исполняется музыка

== Task 2

Отправить *HTTP Request* c *method GET* на servlet с *URL* `/artist/create`, который перенаправит его на jsp-страницу `create-artist.jsp`, содержащую форму для ввода данных об исполнителе.

* Форма отправляет данные в *HTTP Request* c *method POST* на servlet c *URL* `/artist/`, который проводит *data validation*.
** Если имя исполнителя или то, что он является исполнителем русской музыки не указано, тогда servlet должен снова перенаправить на страницу ввода данных
** Если данные указаны верно, тогда servlet должен перенаправить на jsp-страницу `create-artist-success.jsp`, на которой нужно отобразить текст: `Artist saved.`

== Task 3

Отправить *HTTP Request* c *method GET* на servlet c *URL* `/artist/${id}` , который перенаправит его на jsp-страницу `read-artist.jsp`. Страница выводит данные об исполнителе в следующем виде:

----
Id: `${id}`
Имя исполнителя: `${name}`
Язык исполнения: `${language}`
----

== Task 4

Отправить *HTTP Request* c *method GET* на servlet c *URL* `/artists`, который перенаправит его на jsp-страницу `read-artists.jsp`. Страница выводит список всех исполнителей в виде таблицы:

|===
|Id|Имя исполнителя|Язык исполнения
|`${id}`|`${name}`|`${language}`
|===

где `id` является ссылкой, которая при нажатии перенаправит на страницу данного исполнителя.
