= Servlet

== Task 1

Сделать *HTTP Request* c *method GET*, который отправляющий следующие *query parameters*:

* `name`
* `surname`

*Servlet*, принимающий этот запрос, должен вернуть пользователю полное имя.

Если один или несколько параметров не указаны, servlet должен возвращать сообщение об ошибке в зависимости от их количества:

* ``Wrong request. Don't exists '${parameter1}', '${parameter2}' parameters``
* ``Wrong request. Don't exist '${parameter}' parameter``

== Task 2

Создать *form* с вводом имени, телефона и электронной почты.

Создать *servlet*, который будет получать эти данные, и возвращать в виде HTML-страницы.

Если пользователь не ввел данные в какое-либо поле, то возвращается форма с введенными данными, а `input` без данных
имеют красный `border` и сообщение красного цвета рядом с ним `Enter ${data}`.

== Task 3

Создать *servlet*, который по-содержимому *header* *User-Agent* будет определять, с помощью какого браузера пользователь
сделал запрос, и возвращать сообщение вида:

``Приветствую пользователя ${browser-name}``

== Task 4

Создать *servlet* c URI `/send-name`, принимающий *HTTP Request* c *method POST* с `name` и `surname` пользователя и
сохраняющий их в *session*.

== Task 5

Создать *servlet* c URI `/full-name`, принимающий *HTTP Request* c *method GET* получающий из сессии `name` и `surname`
пользователя и возвращающий полное имя пользователя в виде *HTML*-станицы.

== Task 6

Создать *servlet* который получает *HTTP Request* c *method GET* и *query parameter* `id` какой-либо *entity*, которая
хранится в БД. *Servlet* возвращает информацию о *entity* в виде *HTML*-станицы.

* Информацию о *URL*, *username*, *password* базы данных хранить в начальных данных servlet.

== Task 7

Создать страницу с формой для создания *entity*.

Создать *servlet* который получает данные из формы с помощью *HTTP request* c *method POST* и сохраняет её в БД. После
этого передает обработку запроса *servlet*, который может возвращать информацию o *entity* в виде *HTML*-страницы.

* Информацию о *URL*, *username*, *password* базы данных хранить в начальных данных для всех servlets.
